### PR TITLE
Code Review for Issue #15: Display list of items on the Homepage - Student A 

### PR DESCRIPTION
**Pull request by amiraabouhadid**
## Description

In this project, a tasks list structure was generated using javascript bundledthrough webpack. 

### General requirements

- [x] There are no linter errors.
- [x] Followed the **Github flow**.
- [x] The documentation is professional.

### HTML/CSS/JS requirements

- [x] We followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- [x] We followed the list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

### Project requirements

- Home page
- When the page loads, the webapp retrieves data from:
  - The selected API and shows the list of items on screen.

Thank you for taking the time to review this pull request.

### CODE REVIEW

**Comment by mirouhml** [comment]
Hello @amiraabouhadid I am starting the code review!

**Comment by mirouhml** [comment]
Hello @amiraabouhadid, :wave:

Great work on using the Pokeapi to list pokémons and their information on the home page!

## Required Changes ♻️
Try to address the following layout issues: 
- [x] Change heart icon to an empty one that can change later to a full heart when the user clicks on the heart .
- [x] Reduce the number of pokémons on each row so that the cards have room to breath and with that they have increased gap between them.

download (1)

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by amiraabouhadid** [comment]
Hey @mirouhml ,:wave:

I have implemented the changes you mentioned and some more.
  
Here is a list of what I've done: 
- [x]  fixed the navbar to redirect to the home,  types, and abilities pages.
- [x]  added some simple content cards to the types and abilities pages.
- [x]  replaced the full heart icon for the like button with an empty one to be filled when clicked.
- [x]   added a horizontal margin to the cards to leave gaps between them and allow page content to breathe.

Please have a look and let me know if you want other changes. 
download (1)

**Review by mirouhml — APPROVED** [review]
Hello @amiraabouhadid, :wave:

Great work on implementing the changes! There is nothing else to say but it's time to merge it!

## Optional Changes ♻️
- [x] The titles of the types have a scroll bar, shown below in the image:
image
It would be better to fix that, but that's just an optional change!


download (1)

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by amiraabouhadid** [comment]
@mirouhml, 
That is so strange I do not have the scroll bar showing in my version
Screenshot from 2022-03-07 19-53-32
Thanks for approving!

**Pull request merged**
