### PR TITLE
Code review for issue #14: Display Comments pop up with selected item's details - Student B

### PR DESCRIPTION
**Pull request by mirouhml**
### General requirements

- [x] There are no linter errors.
- [x] Followed the **Github flow**.
- [x] The documentation is professional.

### HTML/CSS/JS requirements

- [x] We followed the list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
- [x] We followed the list of [best practices for JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md).

### Project requirements

- Comments popup
- When the popup loads, the webapp retrieves data from:
  - The selected API and shows details about the selected item.

Thank you for taking the time to review this pull request.

### CODE REVIEW

**Comment by amiraabouhadid** [comment]
Hello @mirouhml I'm starting the code review!

**Comment by amiraabouhadid** [comment]
Hello @mirouhml, :wave:

Great work getting a modal to pop up when the comment button is clicked on each pokemon card! 
## Required Changes ♻️
Try to address the following layout issues: 
- [x] align the input, text area, and comment button in the add a comment form to the left
- [x] align the pokemon's characteristics table with the pokemon name
- [x] reduce the size of the image so that the vertical scroll of the modal is unnecessary
- [x] increase the font size of the pokemon's characteristics and perhaps make the "Weight", "Height" etc bold.
- [x] remove the horizontal line separating the x button at the top from the body of the modal and move the x button to be beside the picture as shown in  the given wireframe

download (1)

Cheers and Happy coding!👏👏👏
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mirouhml** [comment]
Hello @amiraabouhadid thanks for the review!

I just finished implementing the following:
- [x] align the input, text area, and comment button in the add a comment form to the left
- [x] align the pokemon's characteristics table with the pokemon name
- [x] reduce the size of the image so that the vertical scroll of the modal is unnecessary
- [x] increase the font size of the pokemon's characteristics and perhaps make the "Weight", "Height" etc bold.
- [x] remove the horizontal line separating the x button at the top from the body of the modal and move the x button to be beside the picture as shown in  the given wireframe

Let me know if you have more suggestions!

**Review by amiraabouhadid — APPROVED** [review]
Good job making the styling changes. Looks good !

**Comment by mirouhml** [comment]
Thanks for the review!

**Pull request merged**
